### PR TITLE
pr_emailer: Enable mail threading

### PR DESCRIPTION
**Pull request by tstellar**

### CODE REVIEW

**Review by preames — APPROVED** [review]
LGTM

Do we have a way to test this?  I'm happy to be the test subject if we do.

**Comment by tstellar** [comment]
I just tested this and it appears to work.  I'll deploy it soon.

**Comment by tstellar** [comment]
These changes have been deployed in production.  Let me know how it looks.

**Comment by preames** [comment]
> These changes have been deployed in production. Let me know how it looks.

Looks to be properly threading for me in Thunderbird.  Thanks!  Much easier to follow after the change.

**Pull request merged**
